title:              The Honeynet Project
email:
description:        Google Summer of Code 2019 Blog
author:             The Honeynet Project
url:                "https://honeynet.github.io/gsoc2019"

# Social Profiles
twitter_username:   ProjectHoneynet
github_username:    honeynet
linkedin_username:  the-honeynet-project

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
